-- Run as database admin. Password provisioning is deliberately separate.
DO $$ BEGIN IF NOT EXISTS (SELECT FROM pg_roles WHERE rolname='fbads_app') THEN CREATE ROLE fbads_app LOGIN; END IF; END $$;
ALTER ROLE fbads_app SET search_path=fbads;
REVOKE ALL ON SCHEMA fbads FROM PUBLIC;
DO $$ BEGIN
 IF EXISTS(SELECT FROM pg_roles WHERE rolname='anon') THEN EXECUTE 'REVOKE ALL ON SCHEMA fbads FROM anon'; END IF;
 IF EXISTS(SELECT FROM pg_roles WHERE rolname='authenticated') THEN EXECUTE 'REVOKE ALL ON SCHEMA fbads FROM authenticated'; END IF;
END $$;
GRANT USAGE ON SCHEMA fbads TO fbads_app;
GRANT SELECT,INSERT,UPDATE,DELETE ON ALL TABLES IN SCHEMA fbads TO fbads_app;
GRANT USAGE,SELECT ON ALL SEQUENCES IN SCHEMA fbads TO fbads_app;
GRANT EXECUTE ON ALL FUNCTIONS IN SCHEMA fbads TO fbads_app;
ALTER DEFAULT PRIVILEGES IN SCHEMA fbads GRANT SELECT,INSERT,UPDATE,DELETE ON TABLES TO fbads_app;
ALTER DEFAULT PRIVILEGES IN SCHEMA fbads GRANT USAGE,SELECT ON SEQUENCES TO fbads_app;
